name: run make_json for the new post

on:
  pull_request:
    types: closed

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: setup python3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: execute python script
        run: |
          python make_jsons.py

      - name: commit files
        run: |
          git config --local user.email "action@noizze.com"
          git config --local user.name "Noizze Blog GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated jsons" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
